// electron_app/scripts/compile_main.js
// Transpila `src/main/main.ts` a `dist/main.js` y lo compila a bytecode V8 (.jsc) con bytenode

const esbuild = require('esbuild');
const bytenode = require('bytenode');
const path = require('path');
const fs = require('fs');
const { app } = require('electron'); // executed inside Electron runtime

const DIST_DIR = path.join(__dirname, '../dist');
const MAIN_JS_PATH = path.join(DIST_DIR, 'main.js');
const MAIN_JSC_PATH = path.join(DIST_DIR, 'main.jsc');
const PRELOAD_JS_PATH = path.join(DIST_DIR, 'preload.js');
const BOOTSTRAP_PATH = path.join(DIST_DIR, 'bootstrap.js');

if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });

console.log('[SECURITY] Transpiling preload.ts -> dist/preload.js');
esbuild.build({
  entryPoints: [path.join(__dirname, '../src/main/preload.ts')],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  outfile: PRELOAD_JS_PATH,
  target: ['node20'],
  sourcemap: false,
  external: ['electron']
}).then(() => {
  console.log('[SECURITY] Transpiling main.ts -> dist/main.js');
  return esbuild.build({
    entryPoints: [path.join(__dirname, '../src/main/main.ts')],
    bundle: true,
    platform: 'node',
    format: 'cjs',
    outfile: MAIN_JS_PATH,
    target: ['node20'],
    sourcemap: false,
    external: ['electron', 'sqlite3', 'pysqlcipher3', 'bytenode', 'electron-updater']
  });
}).then(() => {
  console.log('[SECURITY] Transpiled successfully');

  try {
    console.log(`[SECURITY] Compiling ${MAIN_JS_PATH} -> ${MAIN_JSC_PATH}`);
    bytenode.compileFile({ filename: MAIN_JS_PATH, output: MAIN_JSC_PATH });
    console.log('[SECURITY] Bytecode compiled successfully');

    // generate bootstrap loader
    const bootstrapCode = `// AUTOGENERATED - do not edit\nrequire('bytenode');\nrequire('./main.jsc');`;
    fs.writeFileSync(BOOTSTRAP_PATH, bootstrapCode, 'utf8');

    // remove original js to harden
    fs.unlinkSync(MAIN_JS_PATH);

    console.log('[SECURITY] bootstrap.js created and main.js removed');
    console.log('[SECURITY] Payload secured. Exiting Electron compiler...');
    if (app) app.exit(0);
    process.exit(0);
  } catch (err) {
    console.error('[CRITICAL] bytenode compilation failed:', err);
    if (app) app.exit(1);
    process.exit(1);
  }
}).catch((err) => {
  console.error('[CRITICAL] esbuild failed:', err);
  if (app) app.exit(1);
  process.exit(1);
});

// REGLA DE ARQUITECTURA: Evitar que Electron abra ventanas o se quede colgado
if (app) {
  app.whenReady().then(() => {
    // Solo esperamos a que el código asíncrono superior termine su trabajo.
    // Si Electron inicia completamente antes de que el build termine, esto asegura
    // que no se quede colgado esperando UI.
  });
}
